### ISSUE TITLE
Add river images

### ISSUE THREAD

**Issue by RoyalOughtness** [wayblueorg/wayblue#18]

**Comment by HexSleeves** [comment]
I can take this :)

**Comment by HexSleeves** [comment]
Posted from our discord channel:

https://discord.com/channels/1202304549294190602/1202304549944316007/1211712518481911808
https://discord.com/channels/1202304549294190602/1202304549944316007/1211719825403936848

> I have been trying to figure out how to juggle personal life things that have come up, but im finding myself losing more of my free time atm while I deal with these things :/

I will still be following the project and if I find myself having free time I will attempt to contribute to already made images
