### ISSUE TITLE
wireguard, openvpn, (openconnect)

### ISSUE THREAD

**Issue by boredsquirrel** [wayblueorg/wayblue#30]
#### Wireguard
just has `wireguard-tools` (seems to be already included in "main")

#### OpenVPN
[there are many probably useful base packages](https://packages.fedoraproject.org/search?query=openvpn). At least `openvpn openvpn-otp NetworkManager-openvpn` seem essential.

#### OpenConnect
`openconnect NetworkManager-openconnect`

Not sure about some minimal VPN config tool, probably not minimal enough for those base images?

**Comment by RoyalOughtness** [comment]
https://github.com/wayblueorg/wayblue/commit/b33212283d2a725266b3a3dc3ad6d61caae6207a
