### ISSUE TITLE
battray for laptop battery status

### ISSUE THREAD

**Issue by boredsquirrel** [wayblueorg/wayblue#32]
https://packages.fedoraproject.org/pkgs/battray/battray/

behavior without battery should be tested.

**Comment by trytomakeyouprivate** [comment]
would be cool to not directly lock closed issues. I find this pretty aggressive. Simply overlooked the notification daemon part, sorry

**Comment by RoyalOughtness** [comment]
https://github.com/wayblueorg/wayblue/commit/12169cf52c3c1f56dae416685931416cb9884efe

not configured by default because swaybar and wf-panel already have trays. but it's in the image now if you want to use it

**Comment by RoyalOughtness** [comment]
scratch that, I just noticed that battray is 5 years obsolete and no longer maintained.
