### ISSUE TITLE
notification daemon

### ISSUE THREAD

**Issue by boredsquirrel** [wayblueorg/wayblue#33]
I suppose there has to be one, the same for all Compositors?

https://wiki.archlinux.org/title/Desktop_notifications

- libnotify (base library I think)
- notification-daemon
- dunst
- mako
- dzen2
- stalonetray?

**Comment by RoyalOughtness** [comment]
Please do due diligence and actually check the repo before opening new issues. 

https://github.com/wayblueorg/wayblue/blob/live/config/common-packages.yml#L58
