### ISSUE TITLE
images with gdm

### ISSUE THREAD

**Issue by gmankab** [wayblueorg/wayblue#34]
hello, can you please also make same images, but with gdm instead of sddm

**Comment by RoyalOughtness** [comment]
not unless there's a compelling reason to do so. sericea already includes sddm from upstream and we've already built opinionated changes into the sddm config. 

What issue are you having with SDDM?

**Comment by gmankab** [comment]
i just use gtk + libadwaita software only because qt software looks ugly for me

**Comment by RoyalOughtness** [comment]
Okay, I'm open to adding `-gdm` versions of all existing images, but I don't have time to work on it myself. I'll leave the ticket open for anyone who is interested in working on it.

**Comment by gmankab** [comment]
thanks

**Comment by RoyalOughtness** [comment]
@gmankab 

Added gdm images. There are a few things to keep in mind:

1. The `gdm` package in fedora pulls in gnome-shell, so you need to change the default session selection in GDM via the selector in the bottom right after rebasing.
2. User creation can't be built into images via at this time. This is a tooling issue. So `gdm` is unable to create users on its own behalf. So, you will need to copy over the `gdm` group line and `gdm` user line from `/usr/etc` to `/etc`

**Comment by gmankab** [comment]
thank you❤️
