### ISSUE TITLE
Add  libva-nvidia-driver 

### ISSUE THREAD

**Issue by EpixMan** [wayblueorg/wayblue#41]
I loved the configurations of wayblue (Hyprland-nvidia specifically) and how it made bluebuild beautiful and easy to understand.

Anyway, I just wished if  libva-nvidia-driver could be included as  it is somewhat necessary according to [Rpmfusion](https://rpmfusion.org/Howto/OSTree)

And I wouldn't complain if the codecs were also already installed :)

Thanks again for your cool project.

**Comment by RoyalOughtness** [comment]
> I just wished if libva-nvidia-driver could be included 

It already is included on the nvidia images. run ` rpm -qa | grep libva-nvidia-driver `

> And I wouldn't complain if the codecs were also already installed :)

They are already installed.
