### ISSUE TITLE
Holding a mouse button and pressing a keyboard key disables mouse input

### ISSUE THREAD

**Issue by ribbanya** [wayblueorg/wayblue#55]
I've been struggling with this elusive issue under wayblue-sway for a couple weeks now and didn't know where to post it. I still don't know the root cause.

Basically, if playing a game or using any application that requires mouse and keyboard input simultaneously, if you start holding a mouse button, then press a keyboard button, the mouse cursor will stop responding until all physical mouse buttons are released. I believe it's something to do with the window losing focus but I'm not sure. It can be reproduced easily [here](https://shawon9324.github.io/apps/keytester/).

Initially I tried booting a Live CD of Arch and installing sway-git, then installing Steam and trying a couple games. The issue was not present.

Then I made a COPR of the master branch of sway and wlroots and replaced those packages on wayblue. The issue was still present.

I then installed Bazzite (KDE) and under Plasma the issue was not present. Recently I tried layering sway 1.9 onto that image and logging into sway from the KDE display manager. The issue was not present.

Any suggestions to find the cause of this?

**Comment by RoyalOughtness** [comment]
very strange. can you reproduce this on the upstream `ublue-os/sericea` image? or the upstream of upstream fedora sway atomic image?

**Comment by RoyalOughtness** [comment]
That will help narrow down if this is something wayblue is doing or if there's a bug

**Comment by ribbanya** [comment]
I can test at some point soon. It requires a fresh install from ISO (due to Bazzite and KDE vs. GNOME) so it's a little annoying.

**Comment by RoyalOughtness** [comment]
What do you mean? You can just rebase.

**Comment by ribbanya** [comment]
Last time I tried rebasing from wayblue to Bazzite, it crashed whenever I tried to log into Plasma. On their website it says not to rebase across desktop environments and that it's not supported.

I can try rebasing again anyways.

**Comment by RoyalOughtness** [comment]
yikes. not sure what would cause that

**Comment by ribbanya** [comment]
Yeah, tried rebasing onto wayblue-sway from bazzite just now and it wouldn't even log into TTY. Must be something in `/etc`.

**Comment by ribbanya** [comment]
Okay, the issue is present on stock Sericea. Should I report it to https://github.com/fedora-silverblue/issue-tracker/issues or somewhere else?

**Comment by ribbanya** [comment]
I just wonder whether it's something that's fixed by ublue but not mirrored in the sericea variants.

I'll try a few more images and post the results.

**Comment by ribbanya** [comment]
Okay, tried a bunch of stuff. The ISO used for installation was Fedora Sway Atomic downloaded by Fedora Media Writer.

✔️ = the issue is ABSENT
:x: = the issue is PRESENT

❔|Image
-|-
❌|Fedora Sway Atomic 40
✔️|Fedora Silverblue 40
❌|`ublue/sericea-main`
✔️|Fedora Silverblue 40 under layered `sway`
✔️|`ublue/bluefin`
❌|`wayblueorg/sway`
✔️|`wayblueorg/hyprland`
✔️|`wayblueorg/hyprland` under layered `sway`
✔️|Fedora Sway Spin 40

So it seems to be a problem with the upstream Sway image.

Weirdly it works fine on non-ostree upstream Sway.

**Comment by ribbanya** [comment]
Tracked in https://github.com/fedora-silverblue/issue-tracker/issues/596.
