### ISSUE TITLE
Missing Packages for NetworkManager VPN Configuration

### ISSUE THREAD

**Issue by rehashedsalt** [wayblueorg/wayblue#74]
Not sure if it was rebasing off of ublue back onto Fedora that did it or the recent upgrade to f41, but we lost `NetworkManager-*-gnome` packages for a lot of things, like OpenVPN and OpenConnect. As of right now, if you try to edit a VPN via nm-applet, you get this:

![image](https://github.com/user-attachments/assets/cbc53c40-630e-4627-9816-d2222e89dd3d)

Which is decidedly unhelpful. The actual VPN functionality is there and activating connections works, but you can't edit anything about them from within this UI.

The fix is just to install a handful of packages for the various backends: `NetworkManager-openconnect-gnome.x86_64`, `NetworkManager-openvpn-gnome.x86_64`, `NetworkManager-fortisslvpn-gnome.x86_64`. Not sure if we want every `NetworkManager-*-gnome` package or just a subset.

**Comment by RoyalOughtness** [comment]
doesn't look like ublue ever included these, so it must be something f41 related. If these don't pull in gnome deps, then let's just add all of them
