### ISSUE TITLE
Issues with some user services on SWAY (at least)

### ISSUE THREAD

**Issue by bubuntux** [wayblueorg/wayblue#90]
I have noticed that some services fail most of the time (not always)

running 
```
$ systemctl list-units --user --failed 

  UNIT                                             LOAD   ACTIVE SUB    DESCRIPTION              
● app-blueman@autostart.service                    loaded failed failed Blueman Applet
● app-nm\x2dapplet@autostart.service               loaded failed failed NetworkManager Applet
● app-nvidia\x2dsettings\x2dload@autostart.service loaded failed failed NVIDIA X Server Settings
● dunst.service                                    loaded failed failed Dunst notification daemon
● grub-boot-success.service                        loaded failed failed Mark boot as successful
```

i think the reason may be related (missing env variables somehow),
the failures for nm-applet for example seems to be 
` cannot open display: `
but i run the executed command the applet seems to work just fine. 

seems like the DISPLAY variable is not properly set when running the services, not sure how to troubleshoot this further, any ideas?

**Comment by rehashedsalt** [comment]
What's responsible for starting xwayland, systemd or the compositor? If it's `$DISPLAY` and the compositor is responsible for starting xwayland then these apps could be racing the compositor pushing that envvar to dbus. Just spitballing though -- there are a few reasons why that doesn't make much sense.

Dunst can die on start, it doesn't matter. Whenever something attempts to hit `org.freedesktop.Notifications` it will be reinvoked by systemd and work correctly. Unless you're saying that's happening and it doesn't, in which case we have an issue.

No clue what the hell's going on with `grub-boot-success.service`. Is it unable to write to a file or something?

That said, I don't see these issues over here on Hyprland. ~~Which compositor are you running?~~ nvm caught the title edit

**Comment by bubuntux** [comment]
i'm using sway, seems like an issue only on sway, i re based to hyprland to test and those services and the theming seems to work just fine, with the exception of grub-boot services seems to have issues finding a file

**Comment by bubuntux** [comment]
seems like there maybe an issue upstream that got fix somehow, seems to be working consistently now
